#!/usr/bin/env bash

HOME_DIR=`pwd`
VENV_DIR="${HOME_DIR}/venv"

if [[ ! -d "${VENV_DIR}" ]]; then
    python3 -m venv venv
fi

source "${VENV_DIR}/bin/activate"

REQUIREMENTS="${HOME_DIR}/requirements.txt"

pip install -r ${REQUIREMENTS}
