#!/usr/bin/env bash

HOME_DIR=`pwd`
venvDir="$HOME_DIR/venv"

if [[ ! -d "$venvDir" ]]; then
    python3 -m venv venv
fi

source "${HOME_DIR}/venv/bin/activate"

REQUIREMENTS="${HOME_DIR}/requirements.txt"

pip install -r ${REQUIREMENTS}
